---
title: "Lab 06 - Ugly charts and Simpson's paradox"
author: "Ben Hardin"
date: "2/14/2023"
output: github_document
---

### Load packages and data

```{r load-packages, message = FALSE}
library(tidyverse) 
library(dsbox)
library(mosaicData) 
```

```{r prep-data}
#reading data
staff <- read.csv("data/instructional-staff.csv")

#clean the years
staff <- staff %>%
  rename("1975" = X1975, "1989" = X1989, "1993" = X1993, "1995" = X1995, "1999" = X1999, "2001" = X2001, "2003" = X2003, "2005" = X2005, "2007" = X2007, "2009" = X2009, "2011" = X2011)

#reshaping data
staff_long <- staff %>%
  pivot_longer(cols = -faculty_type, names_to = "year") %>%
  mutate(value = as.numeric(value))

staff_long
```

### Exercise 1

```{r making-first-plot, fig.height = 4, fig.width = 8}
staff_long %>%
  ggplot(aes(x = year, y = value, group = faculty_type, color = faculty_type))+
  geom_line(size = 1.1)+
  geom_point(aes(shape = faculty_type), size = 1.5)+
  theme_bw()+
  labs(title = "Trends in faculty hires (1975 - 2011)",
       y = "Percentage of faculty hires",
       x = "Year",
       color = "Faculty type",
       shape = "Faculty type")
```

### Exercise 2

```{r making-transforming-data}
staff_long <-  staff_long %>%
  mutate(full_time = case_when(
    faculty_type == "Part-Time Faculty" ~ "Part-Time Faculty",
    faculty_type == "Graduate Student Employees" ~ "Graduate Student Employees",
    faculty_type %in% c("Full-Time Tenured Faculty", "Full-Time Tenure-Track Faculty", "Full-Time Non-Tenure-Track Faculty") ~ "Full-Time Faculty"))

staff_full <- aggregate(value ~ year + full_time, data = staff_long, FUN = sum)
```

```{r making-new-plot}
ggplot(data = staff_full, aes(x = year, y = value, group = full_time, color = full_time))+
  geom_line(size = 1.1)+
  geom_point(aes(shape = full_time), size = 1.75)+
  theme_bw()+
  scale_color_manual(values = c("Full-Time Faculty" = "gray50", "Graduate Student Employees" = "gray80", "Part-Time Faculty" = "orange"))+
  labs(title = "Trends in faculty hires (1975 - 2011)",
       y = "Percentage of faculty hires",
       x = "Year",
       color = "Faculty type",
       shape = "Faculty type")
```


### Exercise 3

...

Add exercise headings as needed.
